name: OpenLiberty CI

on:
  workflow_dispatch:
  pull_request:
    branches: 
    - integration
    - gh-actions
    types: [opened, synchronize, reopened, ready_for_review]
    paths-ignore:
      - '.gitignore'
      - '.dockerignore'
      - '*.md'
      - '*.adoc'
      - '*.txt'
      - '.github/ISSUE_TEMPLATE/**'
      - '.dependabot/**'
      - 'cla/**'
      - 'images/**'
      - 'logos/**'
env:
  LANG: en_US.UTF-8
jobs:
  build: #Main build always done on linix run in parallel to setup and unit-test
    name: Build Open Liberty
    runs-on: f64s
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 50
    - name: Set up Java
      uses: joschi/setup-jdk@v2
      with:
        java-version: 11
        openjdk_impl: openj9
    - name: Build with Gradle
      run: |
        cd dev
        chmod +x gradlew
        echo "Building Liberty.  This will take approx. 30 minutes"
        mkdir gradle && touch build.gradle.log
        ./gradlew cnf:initialize assemble > gradle/build.gradle.log
  # cd .. && zip -rq openliberty-image.zip dev/build.image/wlp/
    - name: Upload build failure
      if: failure()
      uses: actions/upload-artifact@v2
      with:
        name: Build failure
        path: dev/gradle/build.gradle.log
      
