name: OpenLiberty CI

on:
  workflow_dispatch:
  pull_request:
    branches: 
    - integration
    - gh-actions
    types: [opened, synchronize, reopened, ready_for_review]
    paths-ignore:
      - '.gitignore'
      - '.dockerignore'
      - '*.md'
      - '*.adoc'
      - '*.txt'
      - '.github/ISSUE_TEMPLATE/**'
      - '.dependabot/**'
      - 'cla/**'
      - 'images/**'
      - 'logos/**'
env:
  LANG: en_US.UTF-8
jobs:
  build:
    name: Build Open Liberty
    runs-on: [f64s]
    outputs:
      test-matrix: ${{ steps.gen-params.outputs.test-matrix }}
      test-os: ${{ steps.gen-params.outputs.test-os }}
      test-java: ${{ steps.gen-params.outputs.test-java }}
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 50
    - name: Validate copyright headers
      if: "github.event_name == 'pull_request'"
      run: .github/workflow-scripts/validate-copyright-headers.sh
    - name: Set up Java
      uses: joschi/setup-jdk@v2
      with:
        java-version: 11
        openjdk_impl: openj9
    - name: Generate output
      id: gen-params
      run: |
        cat > .github/pull_request_body.txt << END_OF_PR_BODY
        ${{ github.event.pull_request.body }}
        END_OF_PR_BODY
        echo "PR Summary is:"
        cat .github/pull_request_body.txt
        git diff --name-only HEAD^...HEAD^2 >> .github/modified_files.diff
        echo "Modified files in this PR are:"
        cat .github/modified_files.diff

        echo "::set-output name=test-os::ubuntu-latest"
        echo "::set-output name=test-java::11"

        MATRIX_RESULT=$(java .github/workflow-scripts/GenerateCategories.java .github/pull_request_body.txt)
        echo "MATRIX_RESULT is $MATRIX_RESULT"
        echo "::set-output name=test-matrix::$MATRIX_RESULT"
    - name: Build with Gradle
      run: |
        cd dev
        chmod +x gradlew
        ./gradlew cnf:initialize assemble
        cd .. && zip -rq openliberty-image.zip dev/build.image/wlp/
    - name: Upload liberty image
      uses: actions/upload-artifact@v2
      with:
        name: openliberty-image
        if-no-files-found: error
        path: openliberty-image.zip

      
